default: generateFiles

generateFiles:
		teitorelaxng --odd --apphome=/Users/emmanuelchateau/Documents/informatique/TEIC/Stylesheets/ theorieSchemaTEI.odd.xml ../schema/theorieSchemaTEI.rng; teitohtml --odd  --profile=gdp theorieSchemaTEI.odd.xml theorieSchemaTEIDoc.html;

# --apphome=/Users/emmanuelchateau/Documents/informatique/TEIC/Stylesheets
